export const patterns = {
  regex: /\/.+\/\w*/g,
  angleBrackets: /<(.+?)>/g,
  comments: /\/\/.+/g,
  openMultiComments: /\/\*.*/g,
  closeMultiComments: /.*\*\//g,
  oneLineMultiComments: /\/\*.*\*\//g,
  openBackQuotes: /`.+/g,
  closeBackQuotes: /.+`/g,
  oneLineBackQuotes: /`.+`/g,
  templateStrings: /(\${)(.+?)(})/g,
  strings: /'.*?'|".*?"/g,
  arguments: /\(([^(]+?)\).*?=>/g,
  keyWords:
    /\b(=>|break|case|class|catch|const|continue|debugger|default|delete|do|else|export|extends|finally|function|for|from|if|import|in|instanceof|let|new|return|super|switch|this|throw|try|typeof|var|void|while|with|yield)\b/g,
  keys: /\w+(?=:)/g,
  literals: /(null|true|false|undefined)\b/g,
  interfaces: /(window|document|console)\b/g,
  objects: /(?<=\.)(\w+)/g,
  numbers: /\b\d+?\b/g,
  words: /\b\w+?\b/g,
  symbols: /[^\w\s~]/g,
  spaces: /\s/g,
  funcNameAndArgs: /(?<=function)(\s+?)(\S+)(\s*?\(\s*?)(.*?)(\s*?\))/g,
  callFunctions: /\w+(?=\s*\()/g,
  allFuncNames: '',
};
