export const patterns = {
  regex: /\/.+\/\w*/g,
  // openBrace: /<\w*?>(\s*?\/\/|$)/g,
  // openClosedBrace: />.+?<\/|<.+?\/>/g,
  // closedBrace: /<\/.+?>(\s*?\/\/|$)/g,
  angleBrace: /<.+>/g,
  // openBrackets: /[{[(:]\s*(\/\/|$)/g,
  // closedBrackets: /^\s*?[}\]\)]/g,
  // openBrackets: /(<\w.*?>|\{|\[|\(|:)(\s*\/\/|$)/g,
  // closedBrackets: /(<\/.*?>|\}|\]|\))(;|\s*?\/\/|$)/g,
  tags: /(<\/?\s*?)(\w*)(>?)/g,
  comments: /\/\/.+/g,
  openMultiComments: /\/\*.*/g,
  closeMultiComments: /.*\*\//g,
  oneLineMultiComments: /\/\*.*\*\//g,
  openBackQuotes: /`.+/g,
  closeBackQuotes: /.+`/g,
  oneLineBackQuotes: /`.+`/g,
  templateStrings: /(\${)(.+?)(})/g,
  strings: /'.*?'|".*?"/g,
  arguments: /\(([^(]+?)\).*?=>/g,
  keyWords:
    /\b(=>|break|case|class|catch|const|continue|debugger|default|delete|do|else|export|extends|finally|function|for|from|if|import|in|instanceof|let|new|return|super|switch|this|throw|try|type|typeof|var|void|while|with|yield)\b/g,
  keys: /\w+(?=:|\s*?=)/g,
  literals: /(null|true|false|undefined)\b/g,
  interfaces: /(window|document|console)\b/g,
  objects: /(?<=\.)(\w+)/g,
  numbers: /\b\d+?\b/g,
  words: /\b\w+?\b/g,
  symbols: /[^\w\s~]/g,
  spaces: /\s/g,
  funcNameAndArgs: /(?<=function)(\s+?)(\S+)(\s*?\(\s*?)(.*?)(\s*?\))/g,
  callFunctions: /\w+(?=\s*\()/g,
  allFuncNames: '',
  allTagsNames:
    /\b(a|abbr|acronym|address|applet|area|article|aside|audio|b|base|basefont|bdi|bdo|big|blockquote|body|br|button|canvas|caption|center|cite|code|col|colgroup|data|datalist|dd|del|details|dfn|dialog|dir|div|dl|dt|em|embed|fieldset|figcaption|figure|font|footer|form|frame|frameset|h1|h2|h3|h4|h5|h6|head|header|hr|html|i|iframe|img|input|ins|kbd|label|legend|li|link|main|map|mark|menu|menuitem|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|picture|pre|progress|q|rp|rt|ruby|s|samp|script|section|select|small|source|span|strike|strong|style|sub|summary|sup|table|tbody|td|textarea|tfoot|th|thead|time|title|tr|track|tt|u|ul|var|video|wbr)\b/g,
};
