export const patterns = {
  regex: /\/.+\/\w*/g,
  // openClosedBrace: />.+?<\/|<.+?\/>/g,
  openAngle: /(^\s*?>|<[^<\/]*?[^\/]>|<\w*?)\s*?(\/\/|\/\*|$)/,
  // closedAngle: /^\s*?(<\/.*?>|\/?>)\s*?(\/\/|\/\*|$)/,
  closedAngle: /^\s*?(<\/.*?>|\/?>)/,
  angleBrace: /(<)|(>)/g,
  openBrackets: /(\{|\[|\(|:)\s*(\/\/|$)/,
  closedBrackets: /^\s*?(\}|\]|\)|break;)/,
  tags: /(<\/?\s*?)(\w*)(>?)/g,
  comments: /\/\/.+/,
  openMultiComments: /\/\*.*/,
  closeMultiComments: /.*\*\//,
  oneLineMultiComments: /\/\*.*\*\//g,
  openBackQuotes: /`.+/,
  closeBackQuotes: /.+`/,
  oneLineBackQuotes: /`.+`/g,
  templateStrings: /(\${)(.+?)(})/g,
  strings: /'.*?'|".*?"/g,
  arguments: /\(([^(]+?)\).*?=>/,
  keyWords:
    /\b(=>|break|case|class|catch|const|continue|debugger|default|delete|do|else|export|extends|finally|function|for|from|if|import|in|instanceof|let|new|return|super|switch|this|throw|try|type|typeof|var|void|while|with|yield)\b/g,
  // keys: /(?<![const|let|var])\s+?(\w+)(?=:|\s*?=)/g,
  keys: /\w+(?=:)/g,
  variables: /(?<!\.)\b\w+(?=\s*?=)/g,
  constants: /(?<!>)\b[A-Z_?]+\b(?!<)/,
  literals: /(null|true|false|undefined)\b/g,
  interfaces: /(window|document|console)\b/g,
  objects: /(?<=\w\.)(\w+)/g,
  numbers: /\b\d+?\b/g,
  words: /\b\w+?\b/g,
  symbols: /[^\w\s~]+/g,
  spaces: /\s+/g,
  funcNameAndArgs: /(?<=function)(\s+?)(\S+)(\s*?\(\s*?)(.*?)(\s*?\))/,
  callFunctions: /\w+(?=\s*\()/g,
  allFuncNames: '',
  allTagsNames:
    /\b(a|u|ul|abbr|div|script|section|select|small|source|span|table|tbody|td|textarea|th|thead|title|tr|body|br|button|canvas|label|legend|li|link|main|acronym|address|h1|h2|h3|h4|h5|h6|head|header|hr|html|font|footer|form|frame|i|iframe|img|input|applet|area|article|aside|audio|b|base|basefont|bdi|bdo|big|blockquote|caption|center|cite|code|col|colgroup|data|datalist|dd|del|details|dfn|dialog|dir|dl|dt|em|embed|fieldset|figcaption|figure|frameset|ins|kbd|map|mark|menu|menuitem|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|picture|pre|progress|q|rp|rt|ruby|s|samp|strike|strong|style|sub|summary|sup|tfoot|time|track|tt|var|video|wbr)\b/,
};
